#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App9.Resource", IsApplication=true)]

namespace App9
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050006
			public const int accordEngine_array = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int camryEngine_array = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int civicEngine_array = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int corollaEngine_array = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int honda_array = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int make_array = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int toyota_array = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int year_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int Engine = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int Make = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int Model = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int Year = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int btnBack = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int btnContinue = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int textView3 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int textView4 = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int textView5 = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int textView6 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Second = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int accordEngine_input = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int camryEngine_input = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int civicEngine_input = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int corollaEngine_input = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int honda_input = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int make_input = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int toyota_input = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int year_input = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
